### ISSUE TITLE
Asynchronous initialization of Spark session is not working

### ISSUE THREAD

**Issue by Gsbreddy** [jupyter-server/enterprise_gateway#788] opened 2020-03-03 19:39 UTC
Hi @kevin-bates ,

I have JEG setup with a VIP and as the requests to JEG increase I see a problem of getting kernels takes very long time.

This being said i came across this [PR](https://github.com/jupyter/enterprise_gateway/pull/81) and [Issue](https://github.com/jupyter/enterprise_gateway/issues/64).

This talks about Asynchronous initialization of Spark session. According to this what i understand is that once the application is in `ACCEPTED` state the notebook should get a kernel and should be able to run non-spark related cells which is not happening currently. The notebook gets the kernel only once the application goes into `RUNNING` state. Please help me understand this.

Thanks.

**Comment by kevin-bates** [comment] 2020-03-03 19:48
Can you provide a complete EG log of the entire kernel startup sequence?  I'll see if I can see anything.  

Question:  What is different between this and #778?  If this _is_ the same instance, I'd prefer we re-open #778 since it has a fairly rich history.

EG should deem the kernel as "started" once a) the application id has been assigned and b) the host information has been returned from the kernel launcher.  Usually, this happens in the ACCEPTED state, but I suppose you could see things have already entered RUNNING, although I'd be surprised.

**Comment by Gsbreddy** [comment] 2020-03-03 19:55
In #778, the problem was due to a curl operation happening in startup folder of ipython which was causing a delay in starting the kernel. 

Here the problem is that once the application id has been assigned and its in `ACCEPTED` state, Notebook doesn't get the kernel up and running. It waits till 40-60 seconds i.e., the time taken till application goes from `ACCEPTED` to `RUNNING` and only then kernel connects to notebook. So for a minute or so, the status on notebook is `No kernel | starting`.

**Comment by kevin-bates** [comment] 2020-03-03 21:02
Ok.  Please provide the log information.  Also, please provide the YARN log (probably `stdout`) that is associated with the ACCEPTED application.

**Comment by Gsbreddy** [comment] 2020-03-05 07:15
I am sorry I can't get any new logs. Please use this logs. https://github.com/jupyter/enterprise_gateway/issues/778#issuecomment-587498113

1. As you can see in the logs, `Jan 31 16:18:42` is when kernel has been requested. An app-id has been assigned and application goes to `ACCEPTED` at `Jan 31 16:18:59`. At this time, the notebook should have a kernel in status `Python | idle`. 

2. But this is not case. It only goes to `idle `state only once the app goes from `ACCEPTED` to `RUNNING` i.e., after a minute or so the notebook has a kernel attached. 

My concern is that if case 1 is what's expected then the time taken for serving a kernel by EG shouldn't take more than 20 sec. (time taken from `SUBMITTED` to `ACCEPTED`) .

If it's the case 2, then time taken is more than a minute to two. (from `SUBMITTED` to `RUNNING`). I am seeing case 2 in my setup. Because of this even if I have a VIP under 2 EG instances, I am not able to scale up the number of requests served by EG since time taken is in order of 60~90sec for the first request and keeps increasing with number of requests in queue and ultimately timing out the requests if this time crosses `KERNEL_LAUNCH_TIMEOUT` which I configured as 4min.

But if case 1 is the expected behavior then this wait time is greatly reduced. But I am not sure how to actually test this. I hope you understood the problem. Any questions?

**Comment by Gsbreddy** [comment] 2020-03-05 07:16
It would be great if you can actually test the YARN cluster mode behaviour and check if  Asynchronous initialization of Spark session is actually working.

**Comment by kevin-bates** [comment] 2020-03-05 18:16
The spark session initialization is not related to the availability of the kernel in the notebook.  All it does is allow the session creation to take place while the rest of the kernel sequence is occurring.  A cell cannot be executed until the kernel is ready.  Once ready, and if the spark context has not finished initializing, attempts to access the context will appear as follows:
![image](https://user-images.githubusercontent.com/22599560/76010566-f29b7a80-5ec7-11ea-8de0-733597926731.png)
A subsequent retry of the cell, once the context has been initialized, will result in the expected output:
![image](https://user-images.githubusercontent.com/22599560/76010646-16f75700-5ec8-11ea-9357-4cdac87c7f6b.png)

Are you using Lab or Notebook?  Your comment about `No kernel` implies Lab.  In either case, the front-end will not send a cell's content to the server until the kernel indicator shows the kernel name (in the case of Lab) or the idle/empty circle (in the case of Notebook).  This change in display happens once the kernel-info request/reply has occurred.

I believe my log analysis has already been provided.  This is about all I have to offer: https://github.com/jupyter/enterprise_gateway/issues/778#issuecomment-587557690.  Its clear, something on the YARN side of things is holding things up.  Please look into the suggestions I provided.

If you can capture complete logs of a scenario, I would be happy to analyze them.  Please include the YARN logs associated with the offending application as well - I think those may be interesting.  Until then, I don't think there's much help I can provide other than what has already been given.

**Comment by Gsbreddy** [comment] 2020-03-05 18:53
Sure. I will get back to you.

**Comment by kevin-bates** [comment] 2022-01-26 23:00
Hi @Gsbreddy - any news on this?  Thanks.

**Comment by kevin-bates** [comment] 2022-05-20 22:55
Closing due to lack of action and non-reproducibility.

**Closed by kevin-bates** 2022-05-20 22:55 UTC
Labels: hadoop yarn, kernels, Spark
