### ISSUE TITLE
Deploy EG on Kubernetes without Cluster-Access

### ISSUE THREAD

**Issue by schmfr** [jupyter-server/enterprise_gateway#885] opened 2020-09-23 16:44 UTC
I am working for a big company where k8s-namespaces are used to isolate the users of the cluster. I can ask for namespaces via email and will recive a service account with full admin rights for that namespace. Nevertheless that account does not have any significant cluster-permissions. In particular it is not allowed to create ClusterRoles or ClusterRoleBindings. These k8s-resources are the reason why my installation of EG on k8s fails. I would like / have to install EG with EG_SHARED_NAMESPACE=true or with pre-created kernel-namespaces. In my opinion both modes of operation should not require cluster-permissions. Is that correct? And which modifications to the helm-chart are necessary make the installation work for my case?

Best regards
Frank

**Comment by kevin-bates** [comment] 2020-09-23 21:16
Hi Frank - thanks for your question.

Enterprise Gateway is intended to be used in multi-user environments where a single EG instance(s) satisfies kernel launch requests across multiple users.  By default, each kernel is launched in its own namespace - which requires clusterrole capabilities.  Users can bring their own namespaces (separate from EG's namespace), but clusterroles are still required for that.  In addition, Spark on Kubernetes requires additional roles to run properly - but I suspect those do not require cluster-level access if you're not spanning namespaces.

I suspect you're correct that in a single namespace environment, introduced via `EG_SHARED_NAMESPACE`, cluster-level roles would not be required. (I've never tried minimizing access for that particular configuration because its really not recommended for how EG is intended to be used.)  That said, I think your use case - essentially that of leveraging EG in a single-user capacity - has utility and it would be great if we could extend this kind of support into our existing helm-chart.

I'm wondering if we could leverage the [`shareGatewayNamespace`](https://github.com/jupyter/enterprise_gateway/blob/master/etc/kubernetes/helm/enterprise-gateway/values.yaml#L20) value in the [`clusterrole.yaml`](https://github.com/jupyter/enterprise_gateway/blob/master/etc/kubernetes/helm/enterprise-gateway/templates/clusterrole.yaml) and [`clusterrolebinding.yaml`](https://github.com/jupyter/enterprise_gateway/blob/master/etc/kubernetes/helm/enterprise-gateway/templates/clusterrolebinding.yaml) files to adjust the applicable `kind:` descriptors from cluster-based levels to regular levels?  At least that's where I would start.  I'm hoping no changes would be required in [`k8s.py`](https://github.com/jupyter/enterprise_gateway/blob/master/enterprise_gateway/services/processproxies/k8s.py) or the [`kernel-pod.yaml.j2`](https://github.com/jupyter/enterprise_gateway/blob/master/etc/kernel-launchers/kubernetes/scripts/kernel-pod.yaml.j2) template, but those are the other locations where additional focus may be required.

Should you find a solution, it would be terrific if you could contribute your changes back to the community.  Please feel free to discuss items as they come up here.  Thanks.

**Comment by telamonian** [comment] 2021-02-16 00:36
I'm in a similar position to @schmfr. I'm currently building a large scale deployment of jeg to large company X's very special cloud platform, which does not allow for dynamic creation/teardown of namespaces.

I can confirm that when `EG_SHARED_NAMESPACE` is set, truncating eg `kind: ClusterRole` to `kind: Role` "just works". The only other thing is that you also need to add an explicit `namespace: ` field to the new `Role` and `RoleBinding` resources.

**Comment by kevin-bates** [comment] 2021-02-16 00:56
Thanks for the update Max!  This sounds like it would be a great "tip" for the docs.

Seems like a small section just prior to [Kernel Image Puller](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/kernel-kubernetes.html#kernel-image-puller) named something like **Operating in Restricted Environments**, then just document these changes, would be sufficient.

Have you tried this with any of the Spark-k8s kernelspecs?

**Comment by telamonian** [comment] 2021-02-16 15:09
> Have you tried this with any of the Spark-k8s kernelspecs?

I am a fan of spark; i've used it extensively in my research work. However, spark is completely irrelevant to my current employer; no one at company X is doing terabyte scale anything. So I don't have any hands on experience with the spark-flavored bits of jeg.

**Comment by kevin-bates** [comment] 2021-02-16 15:32
Thanks @telamonian.  I thought I'd try to sneak this doc update into today's release - so I tried modifying the role and rolebinding yaml scripts - removing 'Cluster' from the `kind:` entries.  However, I kept the namespace non-shared so I could generate the exception, then use a shared namespace.  Much to my surprise, I'm finding that using non-Cluster role and rolebindings still allows the namespace-per-kernel behavior.  This should not be the case.  What am I missing here?  (Sorry, but its been literally years since I visited this stuff.)

**Comment by telamonian** [comment] 2021-02-16 15:52
> Much to my surprise, I'm finding that using non-Cluster role and rolebindings still allows the namespace-per-kernel behavior. This should not be the case. What am I missing here?

To hazard a guess, so long as the `RoleBinding` applies the `Role` to the gateway pod (which, after all, is the one making all of the kube API calls), the gateway pod is still able to spin up/tear down namespaces, pods, and more at  will. So I think the bare minimum here is that the `RoleBinding` and the gateway pod have to be in the same ns? Possibly the `Role` itself has to be in the same ns as well.

As currently written up in the jeg helm chart, the `ClusterRole` bestows a *very* broad set of permissions, which I ended up having to prune significantly for my deployment. So from experience, I believe that if you remove the `"namespaces"` entry from the code below, you'll see your expected error:

https://github.com/jupyter/enterprise_gateway/blob/35f1d72be17c4e514f8883a995597b0c588518c2/etc/kubernetes/helm/enterprise-gateway/templates/clusterrole.yaml#L2-L18

**Comment by kevin-bates** [comment] 2021-02-16 16:40
I don't doubt removing `"namespaces"` from the resources would then prevent EG from creating a per-kernel namespace.  What I'm not following, is how a non-cluster role can create/delete a namespace at all.

**Comment by suryag10** [comment] 2021-02-22 16:19
Hi, There is a way by which we can achieve the same, say the EG is installed in namespace X(with role and rolebinding) and having Service Account SAX, if we want the EG to spawn kernels in namespace Y, then in that case if SAX has enough permissions in Y, then we dont need to have the Clusterrole and Cluster rolebinding for the EG.

**Comment by suryag10** [comment] 2021-02-23 05:49
> Good point. But this could only be achieved if `KERNEL_NAMESPACE` is used (i.e., _Bring Your Own Namespace_), correct? 
[Surya] Correct. Most of the real world deployments where the deployments are being done in public cloud or at customer site wont allow the cluster level permissions. Namespaces are precreated and a admin functionality. 

Since the default behavior is to create a namespace for each kernel pod, cluster-level privs are still required.
> 
> It would be nice to perhaps have value (or two) in the helm chart that when set demotes the role and role bindings from cluster scope. Something like `if (bring_your_namespace or eg_shared_namespace): demote`
[Surya] Yes.

**Comment by kevin-bates** [comment] 2021-02-23 16:48
Thanks @suryag10 - I'm going to mark this as a good first issue since I can't take the time necessary to work this out at the moment.  I think addressing this via helm variables is the way to go.

**Comment by kevin-bates** [comment] 2022-05-20 22:47
I believe this may be resolved with the merging of #1073.  Please visit the updated [Kubernetes deployment information](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/operators/deploy-kubernetes.html#deploying-enterprise-gateway-on-kubernetes).

I'm going to close this issue knowing we can re-open it should it not be resolved.  If not resolved, please include a discussion of what kinds of changes you think are still required.

**Closed by kevin-bates** 2022-05-20 22:47 UTC
Labels: good first issue, kubernetes, configuration
